import { Card } from "./types";
import { START_HERE_TEXT } from "./constants";
import fs from "fs";
import { buildAutoGeneratedCode } from "./util/buildAutoGeneratedCode";

const updateCard = (card: Card, cardPath: string) => {
  const cardFile = fs.readFileSync(cardPath, "utf-8");

  const customCode = cardFile.substring(cardFile.indexOf(START_HERE_TEXT));

  const autoGeneratedCode = buildAutoGeneratedCode(card);

  const data = `
  ${autoGeneratedCode}

  ${customCode}
`.trim();

  return fs.writeFileSync(cardPath, data);
};

export default updateCard;
