import { AUTO_GENERATED } from "../constants";
import { CardType, Card } from "../types";
import buildProperties from "./buildProperties";
import getFileName from "./getFileName";

const CardTypeLabelMap: Record<CardType, string> = {
  [CardType.Resource]: "Resource",
  [CardType.Unit]: "Unit",
  [CardType.Item]: "Item",
  [CardType.Spell]: "Spell",
  [CardType.Building]: "Building",
};

const AUTO_GENERATED_TEXT = `
#region ${AUTO_GENERATED}
// Do not manually change code within the AUTO-GENERATED region. Instead update the Card Library spreadsheet and run npm build-cards`.trim();

export const buildAutoGeneratedCode = (card: Card) => {
  const TYPE_NAME = CardTypeLabelMap[card.Type];

  const fileName = getFileName(card);

  const properties = buildProperties(card);

  return `
${AUTO_GENERATED_TEXT}
public class ${fileName} : Card_${TYPE_NAME}
{
  public ${fileName}()
  {
    ${properties}
  }`.trim();
};
